title: Kyle Mitra # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior at Duke University
  <br><br>
  B.S Biomedical Engineering | B.A Computer Science
  <br><br>
  Certification in Innovation and Entreprenuership
  <br><br>
  <a href="https://www.linkedin.com/in/kylemitra/">View My LinkedIn Profile</a> 
  <br><br>
   <a href="https://kmitra.mystrikingly.com/">View My Personal Portfolio</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
